# Generated by Django 4.2.4 on 2023-09-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='hora',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
